ARG PG_MAJOR=15

FROM postgres:${PG_MAJOR}-alpine
ARG PG_MAJOR

COPY . /tmp/pgvector

RUN apk add --no-cache build-base clang15 llvm15 postgresql${PG_MAJOR}-dev && \
	cd /tmp/pgvector && \
	make clean && \
	make OPTFLAGS="" && \
	make install && \
	mkdir -p /usr/share/doc/pgvector && \
	cp LICENSE README.md /usr/share/doc/pgvector && \
	apk del --no-cache build-base clang15 llvm15 postgresql${PG_MAJOR}-dev && \
	rm -r /tmp/pgvector
